# Generated by Django 5.2.12 on 2026-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('background_gradient', models.CharField(default='linear-gradient(135deg, #0d1b2a 0%, #1a3a5c 60%, #0d47a1 100%)', max_length=255)),
                ('accent_color', models.CharField(default='#4fc3f7', max_length=20)),
                ('link', models.CharField(default='/products', max_length=255)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('badge_text', models.CharField(default='🔥 Hot Deals', max_length=50)),
                ('emoji', models.CharField(default='⚡', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
