# Generated by Django 6.0.1 on 2026-02-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('STUDENT', 'Student'), ('NORMAL', 'Normal')], max_length=20)),
                ('is_student_verified', models.BooleanField(default=False)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('membership_start', models.DateField(auto_now_add=True)),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
