# Generated by Django 6.0.1 on 2026-02-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('educational', 'Educational'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20)),
                ('is_student', models.BooleanField(default=False)),
                ('student_roll_no', models.CharField(blank=True, max_length=30, null=True)),
                ('student_verified', models.BooleanField(default=False)),
                ('semester', models.CharField(max_length=10)),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priority_level', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
        ),
    ]
