# Generated by Django 5.2.12 on 2026-03-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appuser_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
