# Generated by Django 5.2.12 on 2026-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_supplierprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('target_role', models.CharField(default='consumer', max_length=20)),
                ('send_via', models.CharField(default='Email', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='is_opted_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='Sent', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('In-App', 'In-App'), ('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], default='In-App', max_length=20),
        ),
    ]
